MyCRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('crm/', include('crm.urls')),
    path('admin/', admin.site.urls),
]

crm/urls.py
from django.urls import path
from . import views


app_name = 'crm'


urlpatterns = [
    path('', views.login, name='login'),
    path('customer/', views.customer, name='customer'),
    path('service/', views.service, name='service'),
    path('customermanager/', views.customer_manager, name='customer_manager'),
    path('servicemanager/', views.service_manager, name='service_manager'),
    path('logout/', views.logout, name='logout'),
    path('api/announcements/', views.announcements, name='api_announcements'),
    path('api/handover/', views.handover, name='api_handover'),
    path('api/orders/', views.Orders.as_view(), name='api_orders'),
    path('api/orders/<int:z_number>/', views.Orders.as_view(), name='api_order'),
    path('api/comments/', views.comments, name='api_comments'),
    path('api/users/', views.Users.as_view(), name='api_users'),
    path('api/users/<str:role>/', views.Users.as_view(), name='api_usersByRole'),
    path('api/paused_districts/', views.PausedDistricts.as_view(), name='api_paused_districts'),
    path('api/shops/', views.Shops.as_view(), name='api_shops'),
    path('api/groups/', views.group, name='api_group'),

]

templates/base.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MyCRM{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.2/css/all.css" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'crm/images/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'crm/style.css' %}">
    <link href="https://cdn.bootcdn.net/ajax/libs/bootstrap-table/1.18.1/bootstrap-table.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/axios/0.21.0/axios.min.js"></script>
</head>
<body>
{% include 'navbar.html' %}
<div class="container-fluid">
    <div class="row">
        <main class="col-md-10" role="main" style="padding-left: 0px">
            {% block main %}

            {% endblock %}
        </main>


        <div class="d-none d-xl-block col-md-2 bd-toc" aria-label="notice card">
            {% block notice %}

            {% endblock %}
        </div>
    </div>
</div>

<!-- Order Modal -->
<div class="modal fade bd-example-modal-lg" id="order-modal" tabindex="-1" role="dialog"
     aria-labelledby="orderModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div><h5 class="modal-title" id="orderModalTitle">单号：<span class="text-primary"
                                                                           id="orderModalNumber"></span>
                </h5></div>
                <div style="width: 10rem"></div>
                <div><h5 class="modal-title">问题类型：<span class="text-success font-weight-bold"
                                                        id="orderModalQuestionType"></span></h5></div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="orderModalBody">
                <h6>问题描述 <span class="float-right">当前客服：<span class="text-success"
                                                              id="orderModalServiceName">ceshi</span></span>&nbsp;&nbsp;
                </h6>
                <div class="alert alert-info">
                    <pre id="orderModalQuestionText"></pre>
                    <span class="text-right text-primary" id="orderModalCustomer"></span><span
                        id="orderModalCreateTime"></span>
                </div>
                <div id="orderModalCommentList"></div>
                <div id="commentForm">
                    <div class="form-group">
                        {% csrf_token %}
                        <label class="col-form-label" for="orderModalCommentText">处理意见：</label>
                        <textarea class="form-control" name="orderModalCommentText" id="orderModalCommentText" cols="30"
                                  rows="3"></textarea>

                    </div>
                    <div style="text-align: center; width: 100%;">
                        <button type="button" class="btn btn-primary" style="width: 10rem;" id="orderModalSubmit">提交
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<!-- message modal-->
<div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="messageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="messageModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="messageModalBody">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<!-- PausedDistrict modal-->
<div class="modal fade" id="pausedDistrictModal" tabindex="-1" aria-labelledby="pausedDistrictModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pausedDistrictModalLabel">编辑停发地区</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="pausedDistrictModalBody">
                <div id="pausedDistrictForm">
                    <div class="form-group">
                        {% csrf_token %}
                        <label class="col-form-label" for="pausedDistrictForModal"><span class="text-danger">*</span>省份：<span
                                class="text-primary" id="pausedDistrictProvince"></span></label>
                        <div id="pausedDistrictForModal"></div>
                    </div>
                    <div style="text-align: center; width: 100%;">
                        <button type="button" class="btn btn-primary" style="width: 10rem;"
                                id="pausedDistrictModalSubmit">提交
                        </button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" style="width: 10rem;">取消
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- User modal-->
<div class="modal fade" id="userModal" tabindex="-1" role="dialog"
     aria-labelledby="userModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="userModalTitle">用户</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="userModalBody">
                <form>
                    <div class="form-group">
                        <label for="newUserName" class="col-form-label"><span
                                class="text-danger">*</span>用户名：</label>
                        <input type="text" class="form-control" id="newUserName" placeholder="用户名一旦创建无法修改，请认真核对！">
                    </div>
                    <div class="form-group">
                        <label for="newUserPhone" class="col-form-label"><span
                                class="text-danger">*</span>联系电话：</label>
                        <input type="number" class="form-control" id="newUserPhone">
                    </div>
                </form>
                <p class="text-info">温馨提示：新创建用户默认密码为：123456，首次登陆系统需要强制修改密码。</p>

                <div style="text-align: center; width: 100%;">
                    <button type="button" class="btn btn-primary" style="width: 10rem;" id="userModalSubmit">提交
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- Group modal-->
<div class="modal fade" id="groupModal" tabindex="-1" role="dialog"
     aria-labelledby="groupModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">群组</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <input type="text" style="display: none" id="groupModalAction">
                        <label for="newGroupName" class="col-form-label"><span
                                class="text-danger">*</span>群组名称：</label>
                        <input type="text" class="form-control" id="newGroupName" placeholder="群组名称一旦创建无法修改，请认真核对！">
                    </div>
                    <div class="form-group">
                        <label for="newAddress" class="col-form-label"><span
                                class="text-danger">*</span>群组地址：</label>
                        <input type="text" class="form-control" id="newAddress">
                    </div>
                </form>
                <p class="text-info">温馨提示：群组地址用于拦截改地址，客户提交拦截件实际生成改地址件并改为群组所在地址。</p>

                <div style="text-align: center; width: 100%;">
                    <button type="button" class="btn btn-primary" style="width: 10rem;" id="groupModalSubmit">提交
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- Shop modal-->
<div class="modal fade" id="shopModal" tabindex="-1" role="dialog"
     aria-labelledby="shopModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="shopModalTitle">店铺</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="shopModalBody">
                <div class="form-group">
                    <label for="newShopName" class="col-form-label"><span
                            class="text-danger">*</span>店铺名称：</label>
                    <input type="text" class="form-control" id="newShopName">
                    <label for="newShopkeeper" class="col-form-label"><span
                            class="text-danger">*</span>客户：</label>
                    <input type="text" class="form-control" id="newShopkeeper">
                </div>

                <div style="text-align: center; width: 100%;">
                    <button type="button" class="btn btn-primary" style="width: 10rem;" id="shopModalSubmit">提交
                    </button>
                </div>
            </div>
        </div>

    </div>
</div>

{% block change_pwd %}
    <!-- Change_pwd modal-->
    <div class="modal fade" id="change_pwdModal" tabindex="-1" role="dialog"
         aria-labelledby="change_pwdModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">修改密码</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="originalPassword" class="col-form-label"><span
                                class="text-danger">*</span>原密码：<span class="text-secondary">密码长度为6-14位</span></label>
                        <input type="password" class="form-control" id="originalPassword" maxlength="14">
                        <label for="newPassword1" class="col-form-label"><span
                                class="text-danger">*</span>新密码：</label>
                        <input type="password" class="form-control" id="newPassword1" maxlength="14">
                        <label for="newPassword2" class="col-form-label"><span
                                class="text-danger">*</span>重复新密码：</label>
                        <input type="password" class="form-control" id="newPassword2" maxlength="14">
                    </div>

                    <div style="text-align: center; width: 100%;">
                        <button type="button" class="btn btn-primary" style="width: 10rem;" id="change_pwdSubmit">提交
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block modal %}

{% endblock %}

</body>
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/bootstrap-table/1.18.1/bootstrap-table.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/bootstrap-table/1.18.1/locale/bootstrap-table-zh-CN.js"></script>
<script src="/static/crm/mycrm.js"></script>

</html>

templates/navbar.html
<header>
    <nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        {% if group_name %}
            <span class="navbar-brand">{{ group_name }}</span>
        {% else %}
            <h2 class="navbar-brand">客服工单系统</h2>
        {% endif %}
    <div class="justify-content-end">
          {% if username %}
              <span class="navbar-text">欢迎！{{ username }}</span>&nbsp;&nbsp;
              <button class="btn btn-link text-light my-2 my-sm-0" data-toggle="modal"
                                        data-target="#change_pwdModal">修改密码</button>
              <a href="{% url 'crm:logout' %}" class="btn btn-outline-warning my-2 my-sm-0" role="button">退出</a>
          {% else %}
              <a href="{% url 'crm:login' %}" class="btn btn-outline-success my-2 my-sm-0" role="button">请登录！</a>
          {% endif %}
    </div>
    </div>
    </nav>
</header>